### ISSUE TITLE
FTP and SMB not connecting

### ISSUE THREAD

**Issue by Brutal-sam** [cy33hc/ps4-ezremote-client#1]
So I've been testing the app on ps4 9.00 and webDAV works fine but ftp and smb don't connect, I get an error 426 connection timedout, here's the twist though, I tried connecting the old independent apps smb and ftp to see if my servers are working and they both connected fine no issues, however smb v1.10 couldn't connect either, I had to use the 1.01 build.
Tested on ps4 9.00 goldhen 2.3 and default ports.

**Comment by cy33hc** [comment]
@Brutal-sam Are you specifying the correct url format as documented in the project page?

**Comment by Brutal-sam** [comment]
@cy33hc yes, I typed them correctly like this ftp://192.168.1.3:21 where can I find a log to send it to you?

**Comment by Brutal-sam** [comment]
ftp issue was fixed by simply adding a username without password, I had no username before but adding it fixed the issue, now it's just smb that's still not connecting 
Uploading Base Profile 2023.02.10 - 13.11.58.01.mp4…

**Comment by Brutal-sam** [comment]
![cxcxc](https://user-images.githubusercontent.com/94696121/218099347-c8b74669-beec-4c95-b422-9c36b422c76a.PNG)
smb issue was fixed by entering my PC username and password :)
