### ISSUE TITLE
Include payload?

### ISSUE THREAD

**Issue by ProfDrLuigi** [cy33hc/ps4-ezremote-client#12]
Perhaps you can include the goldhen 9.00 files? Would be nice to have the hosting of the JB in this package too.

[ps4.zip](https://github.com/cy33hc/ps4-ezremote-client/files/12342093/ps4.zip)

**Comment by cy33hc** [comment]
@ProfDrLuigi This is not very useful. Since app can only be launched after Goldhen payload has being loaded.
