### ISSUE TITLE
Unable to extract password protected compressed files

### ISSUE THREAD

**Issue by PSInstaller** [cy33hc/ps4-ezremote-client#14]
Can I extract password protected compressed files with password input or how to do?

**Comment by cy33hc** [comment]
@PSInstaller password protected zips aren't supported. I can try add support but can't guarantee if the library I'm using supports it.

**Comment by PSInstaller** [comment]
Okay that's why I found no solution anywhere. Please do add and I'm hoping that'll work. This app is pretty helpful and great.

**Comment by cy33hc** [comment]
@PSInstaller zipcrypt password protected zip files implemented in 1.11... winzip (aes-128/256) not supported.

**Comment by PSInstaller** [comment]
@cy33hc WOW! Thank you, for considering my point and updating the app. I will update and test the app in my ps4.

**Comment by cy33hc** [comment]
@PSInstaller Just released 1.12. Now supports all kinds of password protected zip files.
