### ISSUE TITLE
Unable to RPI with WebDAV on Snology NAS

### ISSUE THREAD

**Issue by qwayxwq** [cy33hc/ps4-ezremote-client#16]
WEBDAV is running in Synology NAS
5.05 firmware with Goldhen 2.3

With RPI box ticked, every time I click “install”, it pops a “can’t download” message on top left corner eventually.
Alternatively, I can download and install with RPI box unticked.
The WebDAV service can’t go completely anonymous, it requires ” anonymous “ as an username, could it be the cause?
Appreciate for your brilliant work!

**Comment by cy33hc** [comment]
@qwayxwq It shouldn't be a problem with having a username/password at least in the latest version of ezremote client 1.10.

What version of ezremote client are you using? Also under notification for the failed install and get the notification error message and post it here.

**Comment by qwayxwq** [comment]
@cy33hc its version 1.10 I’m using.
The error message says:” an error occurred on the server.(HTTP status code:400)(CE-40848-4)

**Comment by cy33hc** [comment]
@qwayxwq I had re-tested installing from 4 different webdav servers and it's working fine. I don't have Synology NAS to troubleshoot this particular problem. If filename/directory contains spaces or special characters, try removing it and try again.

Alternatively, Synology support FTP, you can also RPI with FTP.

**Comment by qwayxwq** [comment]
@cy33hc Same error occurred for FTP, it seemed that  synology rejected the connection from RPI, it only allowed me to download first and install.
WEBDAV works fine on PC , though, it is most likely the NAS that causes the problem.
Anyway, thanks a lot for your excellent work.

**Comment by cy33hc** [comment]
@qwayxwq I think the NAS might be blocking the request during RPI because there are a lot of request made in a short period, and NAS thinks there is a DOS(denial of service) attack. See if there's any config in the NAS that you can increase this limit.

**Comment by cy33hc** [comment]
@qwayxwq This is fixed in v1.22. https://github.com/cy33hc/ps4-ezremote-client/releases/tag/1.22

**Comment by cy33hc** [comment]
Closing due to no response from reporter
