### ISSUE TITLE
Failed install game update via Samba

### ISSUE THREAD

**Issue by Mantikor** [cy33hc/ps4-ezremote-client#17]
Main file with game was installed successfully, but installation of update was failed.
![image](https://github.com/cy33hc/ps4-ezremote-client/assets/17388366/e3458ad0-9827-435b-8fcb-4496feced16a)
Using GoldHEN installer and usb flashcard I installed this update without any problem.

**Comment by cy33hc** [comment]
@Mantikor I checked an it's able to install patch pkgs. I did notice however that the samba failed on a second attempt to install pkg right away on some occasions. Workaround is to disconnect samba and re-connect and you should be able to install again. Meanwhile, I will check what is causing the occasional failure.

**Comment by Mantikor** [comment]
@cy33hc, thanx for answer! It's not a first problem, but the problem always only with installation patch or dlc pkgs, not with the main. Sorry,  but I found time for report only now :( Will be report about next failures if it's will be :) Problem 100% not in SAMBA server. All next pkgs installed without any problems and without server restart. Maybe long filename the cause of error... Will observe. Maybe I can switch DEBUG mode (or smth. else) with error logging and save logs and send it to you?

**Comment by cy33hc** [comment]
@Mantikor Thx. I will try the update pkg in the screenshot and see if I can reproduce.

**Comment by Mantikor** [comment]
@cy33hc if u need I can upload this main and update pkgs to google drive/mail.ru cloud or send to u magnet link (so, very slow download)

**Comment by cy33hc** [comment]
@Mantikor I reproduced the error. I can troubleshoot, no need for any logs

**Comment by cy33hc** [comment]
@Mantikor Try this package and see if it's fixed. https://www.mediafire.com/file/615000ibigtmxca/ezremote_client.pkg/file

**Comment by Mantikor** [comment]
@cy33hc, I have tested this new version and it's works fine! The patch was successfully installed! Thanx for bugfix and waiting for [Transfer speed feature](https://github.com/cy33hc/ps4-ezremote-client/issues/15)!
