### ISSUE TITLE
Latest version cannot use WebDAV for RPI on Snology NAS

### ISSUE THREAD

**Issue by fynhnt** [cy33hc/ps4-ezremote-client#18]
WEBDAV is running in Synology NAS 6.72 firmware with GoldHen2.4b16.2

With RPI box ticked, every time I click “install”, it pops a “can’t download” message on top left corner eventually.Alternatively, I can download and install with RPI box unticked.

Rolling back to version 1.18 works fine, but the latest versions have errors.
![20240314_211624_00201833](https://github.com/cy33hc/ps4-ezremote-client/assets/121024319/c6c76ec1-0fce-489f-989c-a3a12baeb2b7)
![20240314_211309_00366986](https://github.com/cy33hc/ps4-ezremote-client/assets/121024319/30592f2a-53b6-4cf9-bb0c-00a957173603)

**Comment by cy33hc** [comment]
@fynhnt Thx for reporting. Probably related to unicode chars.

**Comment by cy33hc** [comment]
@fynhnt This is fixed in v1.22. https://github.com/cy33hc/ps4-ezremote-client/releases/tag/1.22

**Comment by 76892881** [comment]
[cy33hc](https://github.com/cy33hc) 1.22 still has this bug,can’t download and can’t install， 1.18 is normal。

**Comment by cy33hc** [comment]
@fynhnt Can you download the mediafire package to capture the logs. After download, extract and install the ezremote_client.pkg file in the zip. Then execute the "runme.bat", it will start capturing the log in a file called "debug.log". On the PS4, try install and pkg from webdav through RPI. After that, just terminate runme.bat. Then you can upload the debog.log file here.

https://www.mediafire.com/file/kxot3seiortoqvn/socat-1.7.3.2-1-x86_64.zip/file

**Comment by fynhnt** [comment]
> @fynhnt Can you download the mediafire package to capture the logs. After download, extract and install the ezremote_client.pkg file in the zip. Then execute the "runme.bat", it will start capturing the log in a file called "debug.log". On the PS4, try install and pkg from webdav through RPI. After that, just terminate runme.bat. Then you can upload the debog.log file here.
> 
> https://www.mediafire.com/file/wmv05c1h7b2cw0g/socat-1.7.3.2-1-x86_64.zip/file

Whether it is mediafire or releases, I tested that v1.22 can install PKG normally.
[debug.log](https://github.com/cy33hc/ps4-ezremote-client/files/14717551/debug.log)

**Comment by cy33hc** [comment]
@fynhnt Ok. I will close this issue then.

**Comment by cy33hc** [comment]
> @cy33hc 1.22 still has this bug,can’t download and can’t install， 1.18 is normal。

Can you test again? fynhnt was able to install.

**Comment by cy33hc** [comment]
Closing due to no respond

**Comment by cy33hc** [comment]
@76892881 Please test WebDAV again on Snology NAS. I made some code change related to WebDAV in release v1.27. See if it fixes the problem.
