### ISSUE TITLE
The Chinese font library is missing

### ISSUE THREAD

**Issue by fynhnt** [cy33hc/ps4-ezremote-client#2]
![ezRemote](https://user-images.githubusercontent.com/121024319/218299917-a70c1710-11ec-460c-9213-08a7b07065b3.png)

**Comment by cy33hc** [comment]
@fynhnt Is this traditional or simplified Chinese?

**Comment by cy33hc** [comment]
@fynhnt I used imgui library and used the GetGlyphRangesChineseSimplifiedCommon() which is faster, but excludes some characters . I'll change to GetGlyphRangesChineseFull(), but the app might take a little longer to load.

https://github.com/ocornut/imgui/issues/1859

**Comment by fynhnt** [comment]
> @fynhnt我使用了 imgui 库并使用了速度更快但排除了一些字符的 GetGlyphRangesChineseSimplifiedCommon() 。我将更改为 GetGlyphRangesChineseFull()，但应用程序可能需要更长的时间才能加载。
> 
> 你能不能试试改成“Chinese Traditional”，看看你能不能看到那些字符？
> 
> [ocornut/imgui#1859](https://github.com/ocornut/imgui/issues/1859)

改成“Chinese Traditional”，正常。

![20230213_130536_00470858](https://user-images.githubusercontent.com/121024319/218372464-65769d39-7af4-4dcd-8643-89b1645c5e1d.jpg)

**Comment by fynhnt** [comment]
> @fynhnt I used imgui library and used the GetGlyphRangesChineseSimplifiedCommon() which is faster, but excludes some characters . I'll change to GetGlyphRangesChineseFull(), but the app might take a little longer to load.
> 
> Can you try to change to "Chinese Traditional" and see if you can see those characters?
> 
> [ocornut/imgui#1859](https://github.com/ocornut/imgui/issues/1859)

Select "Chinese Traditional" as normal.

Installed PKG successfully the first time, and never again. The one that succeeded was still the Synology NAS administrator account password. It also failed to use anonymous access as prompted. Please tell me how to solve it, thank you!

![快照1](https://user-images.githubusercontent.com/121024319/218392174-3379b86b-05ba-4676-bc99-ea3b248d1e1c.png)

![快照2](https://user-images.githubusercontent.com/121024319/218392251-14f57b28-8644-4ca6-8c5b-533ed37ba59b.png)

![20230213_143047_00858865](https://user-images.githubusercontent.com/121024319/218392063-f7e76025-82dd-4972-9b0c-ce64c0a2d02c.jpg)

![20230213_144720_00631783](https://user-images.githubusercontent.com/121024319/218392108-e7d3207b-84c2-4b3a-9893-044f367baa2d.jpg)

**Comment by cy33hc** [comment]
@fynhnt That is not 100% anonymous. It still need user called "anonymous". Pure anonymous doesn't need username and password, so the PS4 won't be able to download. Sorry.

**Comment by fynhnt** [comment]
> @fynhnt That is not 100% anonymous. It still need user called "anonymous". Pure anonymous doesn't need username and password, so the PS4 won't be able to download. Sorry.

Please add Chinese support for the text file, now it is garbled, this function is really great, thanks again!

**Comment by cy33hc** [comment]
@fynhnt Can you attach a screenshot?

**Comment by fynhnt** [comment]
> @fynhnt Can you attach a screenshot?

For cheats in PKG format, I usually attach a description file, which makes it easy to distinguish the differences between versions. It would be even better if the picture preview function can be added in the future, thanks again!

![20230309_085612_00944819](https://user-images.githubusercontent.com/121024319/223888200-3e6c49a7-9fa7-4feb-8092-59321f4a84e3.jpg)

**Comment by cy33hc** [comment]
@fynhnt Thx for the screenshot. I don't know chinese so I don't know how to create a test file. Is it ok if you send me the sample file that you are showing.

**Comment by cy33hc** [comment]
@fynhnt I edited the "Simplified Chinese.ini" language file and everything look ok. Did you save the file in UTF-16 encoding. Try saving the file in UTF-8 encoding.
![image](https://user-images.githubusercontent.com/4947747/224254807-1ab76b60-6a55-4689-8a08-c7bf1267294c.png)
