### ISSUE TITLE
[Feature request] Browsing the last item in the directory, press down key to return to the first item.

### ISSUE THREAD

**Issue by applekiller7** [cy33hc/ps4-ezremote-client#21]
Browsing the last item in the directory, press down key to return to the first item. Similarly, pressing the up key while browsing the first item will jump to the last item.
This is very helpful for users who have a lot of items in one directory.

**Comment by HVR88** [comment]
This is called "wrap around" - good suggestion

**Comment by cy33hc** [comment]
@HVR88 @applekiller7 Implemented in release https://github.com/cy33hc/ps4-ezremote-client/releases/tag/1.25
