### ISSUE TITLE
Install not working on 11

### ISSUE THREAD

**Issue by KillahB33** [cy33hc/ps4-ezremote-client#22]
I can't get install to work on 11 from WebDAV, it seems to add it to the notifications saying it's downloading and then fails at the playable state ( abround 26gb of the 80gb and change install) saying it's not available on 11 and I need to update to 11.02
Main game using gold hen seems to have installed ok and I'm currently installing the patch but it's slow cause it's reading it from the same hard drive it's installing from. Thankfully copy worked well so i used that no put it on the hard drive then do the install. 

UPDATE: Confirmed install went well after copying locally and then installing. Though way slower which sucks

**Comment by cy33hc** [comment]
@KillahB33 Let me know what Game and TitleID. It'll try install myself to see what's causing it.

**Comment by KillahB33** [comment]
OH interesting! GOW didn't have that issue after install, but Tsuchima did. But it did it after the install.
I thought I had disabled that so it's now disabled. I'll attempt again. I have seen people having better luck with ftp, wondering what your thoughts are on the best protocol I should be using. 

I have added the IP blocks to the DNS that my PS4 is currently pointed to.

**Comment by KillahB33** [comment]
@cy33hc are you on 11?
I just tried horizon forbidden west cusa28561 and it's failing too.

**Comment by cy33hc** [comment]
@KillahB33 I'm on 11.00. Do you happen to be using a Synology NAS? Couple of people have problems with it. If yes, are you able to look at the NAS logs to see if there are any error. I'm running a webdav server from PC.

because, the ps4 installer, doesn't download the pkg in one request through the net. it downloads in chunks of 16MB, so the NAS could get hundreds or thousands of request. I'm wondering if there is some kind of protection on the NAS for DDOS Attack.

when install from disk, ps4 uses a differrent method to install so  you don't have the problem

**Comment by KillahB33** [comment]
Interesting. No it's an unraid NAS, I'll try again today and watch the logs on there and update you.

Ok cool, I'll switch back to webdav! I was previously running the webdav service from a vm seperate from unraid with an NFS mount. I have now moved that docker containers on to unraid it's self so I was hoping that would help, it seemed to help a little with speeds and issues with stale file handles but it still doesn't seem to want to install.

**Comment by cy33hc** [comment]
@KillahB33 I use dufs (https://github.com/sigoden/dufs) for webdav which hasn't given any problems.

**Comment by KillahB33** [comment]
Seems I am not the only one, I don't think Stray is really that big but who knows.
https://www.reddit.com/r/ps4homebrew/comments/1cx4u73/getting_error_ce362449_on_large_games/

**Comment by yasdev08** [comment]
> Seems I am not the only one, I don't think Stray is really that big but who knows.
> 
> https://www.reddit.com/r/ps4homebrew/comments/1cx4u73/getting_error_ce362449_on_large_games/

It's not stray it's god of war

**Comment by cy33hc** [comment]
@KillahB33 @yasdev08 If you're on NAS, is there a settings for DDOS protection? Can probably disable or change the threshold. 
At least on Synology NAS there is, I don't own a NAS so might not be on all NAS. https://kb.synology.com/en-ca/DSM/help/DSM/AdminCenter/connection_security_dos_vpnpassthrough?version=6

**Comment by KillahB33** [comment]
@cy33hc I know my issue isn't DDOS as it doesn't appear unraid has that option. I am guessing with Horizon it was a bad game. I have finished tsuchima, so I am going to uninstall then test with that and report back.

**Comment by KillahB33** [comment]
Alright i think we can close this. Was able to install ghost of tsuchima and it's 40gb, I'm trying gt sport again and hoping that works.
Out of curiousity @cy33hc what type of disk are you reading from and what's in your PS4. Mine are both HDD so I'm wondering if it's a speed issue. I have a cache drive on by nas so i could speed reads up.
