### ISSUE TITLE
Unable to connect to SMB share folder on Mac (macOS 14, ARM machine) from PS4 11.00 - keep getting STATUS_LOGON_FAILURE.

### ISSUE THREAD

**Issue by serista** [cy33hc/ps4-ezremote-client#24]
macOS 14 - file sharing enabled in the settings, share folder set, users set.

PS4 11.00 - I enter smb://192.168.1.3/!PS4 in the addr field (!PS4 - my share folder name), and my login/password (of course the user also listed in the macOS file sharing settings).

All I get is error STATUS_LOGON_FAILURE in red at the bottom of the window.

**Comment by cy33hc** [comment]
@serista Try remove the exclamation sign from the share name. Try not to use special chars in the share name

**Comment by serista** [comment]
> @serista Try remove the exclamation sign from the share name. Try not to use special chars in the share name

Nope. Any folder gives that error.

**Comment by cy33hc** [comment]
@serista I'm not a Mac user, but I had installed "Big Sir" into VirtualBox and got Sharing working. At least for me I had to turn on the "Windows Sharing" option for the user. See screenshot

![Screenshot at 2024-06-14 20-45-54](https://github.com/cy33hc/ps4-ezremote-client/assets/4947747/fdb0d313-69e7-4570-aaad-39e37d249bdc)

![Screenshot at 2024-06-14 20-46-40](https://github.com/cy33hc/ps4-ezremote-client/assets/4947747/89741185-05e3-45ad-8420-c71552add47f)

**Comment by serista** [comment]
Yes, it was enabled. I guess it's a problem of 14._**0**_
