### ISSUE TITLE
Can`t install some pkgs from NAS 

### ISSUE THREAD

**Issue by Felixpremier** [cy33hc/ps4-ezremote-client#27]
First I want to thank all of you for this wonderful gift that spare me from using pc as a connector in between PS4 console and my NAS.  It`s quite convenient and fast speed.
However, i notice a repetitive issue, maybe it is only for me: I am on 9.00, and sometimes ,  I can install the base PKG without any problem. but for patches, the popup window will remain for several seconds and feed me back with 1 failed notice. I tried 3 different games, and it kept happening even after I renamed those files to make it shorter, and directory is totally in English. Later I downloaded those patches to a flash-drive and install them directly from usb-port on PS4, it worked just fine so the files seem flawless. 
Thank you again and look forward for any suggestion. 
![D5238FDD-22EB-4C70-9980-567519DFB895-678-000001257548504F](https://github.com/cy33hc/ps4-ezremote-client/assets/172558749/98f29950-70f3-4a3b-8a90-44737c950f11)

**Comment by cy33hc** [comment]
@Felixpremier You don't need put in usb and then copy to PS4 to install. Alternatively, you can just download the file to the /data/pkg folder and then install directly from the app or uncheck "RPI" and it will auto download to PS4 first and then install. I fixed a couple of issues earlier related to installing patches. Are you using latest version 1.24?

But I'll take a look at the particular patch file you have in screenshot and try repro myself to see.

**Comment by Felixpremier** [comment]
@cy33hc thank you for this fast reply. 
Yes, I am on the latest 1.24, I remember download one of those patches by accident but I can not find it anymore….
Anyway, I will try my suggestion once I am home and allow me get back to you.
Thx.

**Comment by cy33hc** [comment]
@Felixpremier Ok. I reproduced the issue. I will see what's causing it.

**Comment by Felixpremier** [comment]
@cy33hc just a thought: maybe those pkg dumped from higher FW such as 11.00, normally, only by installing backport patches can base pkg work on my 9.00. Don`t know if this cause the issue since I  only tried a few game.

**Comment by Felixpremier** [comment]
@cy33hc as you suggested, I can download patches to  PS4 hhd then successfully install. The only problem is that takes twice space and a bit more time.

**Comment by cy33hc** [comment]
@Felixpremier Just a workaround for now. Looking into the problem.

**Comment by cy33hc** [comment]
@Felixpremier Got a fix, will release in a couple of days

**Comment by Felixpremier** [comment]
@cy33hc Great! Thx

**Comment by cy33hc** [comment]
@Felixpremier Fixed in release https://github.com/cy33hc/ps4-ezremote-client/releases/tag/1.25

**Comment by Felixpremier** [comment]
Thank you so much
