### ISSUE TITLE
Can't install v1.27

### ISSUE THREAD

**Issue by steve51184** [cy33hc/ps4-ezremote-client#28]
Tried to install but fails 

Tried to uninstall old version then install but still won't install

Rebooted and no matter what I try it still won't install

Now I have no app installed :(

![IMG_20240628_201013](https://github.com/cy33hc/ps4-ezremote-client/assets/12534098/1c7be76f-7102-4fb3-a499-426dfbafde30)

Goldhen, 9.0, PS4 pro

**Comment by cy33hc** [comment]
Are you using ezremote-client to install itself. That won't work. Always use goldhen installer to install ezremote-client. My app can't update itself.

**Comment by steve51184** [comment]
I uninstalled it so yes using goldhen package installer and it still fails

**Comment by cy33hc** [comment]
Then the previous installation is still in the Download sections. Go to the notifications and delete all occurence of the app, includes "Options Menu" -> "Downloads".

**Comment by steve51184** [comment]
Yeah I've cleared that it's empty nothing in there and no app installed but same issue

**Comment by cy33hc** [comment]
Oh. It's a digest error. Looks like a corrupt pkg. Let me upload again

**Comment by cy33hc** [comment]
@steve51184 Re-uploaded the pkg to git. Can you try again.

**Comment by steve51184** [comment]
Installed Ty 😁
