### ISSUE TITLE
Use a button to go up a directory.

### ISSUE THREAD

**Issue by ismalopese** [cy33hc/ps4-ezremote-client#29]
Searching for a file in multiple folders with a lot of files could be made less time consuming assigning a button to go up a directory, instead of going everytime to the first item in the folder (the warp around feature doesn't help with this either). 

L2/R2 appear to be unassing, so maybe using L2 for going up a directory in the left pane when selected, and R2 for the right one may make that task a lot easier. 

No idea how to implement this, so I just throw to you the suggestion :)

**Comment by cy33hc** [comment]
@ismalopese Yeah. That's doable.

**Comment by cy33hc** [comment]
@ismalopese This is implemented in release 1.28 https://github.com/cy33hc/ps4-ezremote-client/releases/tag/1.28
