### ISSUE TITLE
"426 Connection closed" when trying to access http server

### ISSUE THREAD

**Issue by lsahnicne** [cy33hc/ps4-ezremote-client#3]
I have an http server set up on my NAS to use with [PS4 SMB Client](https://github.com/cy33hc/ps4-smb-client) to install games remotely and it works. However, when I try to access said server with this application, I  get a "426 Connection closed." error.

![11](https://user-images.githubusercontent.com/43319094/218314544-0f20991b-ee7a-435c-a854-5cafb8b1df37.jpg)

![ezRemote Client_20230212164305](https://user-images.githubusercontent.com/43319094/218314549-615b0f47-9029-4b47-bad1-1f824f4e137f.jpg)

**Comment by cy33hc** [comment]
@lsahnicne I didn't port over the install from http server with the standalone smb client. The http URL that you put in the site needs to be a WebDAV server. WebDAV is an extension of http, so just regular http server will not work. I will add back the option later for install form http server with smb.

**Comment by cy33hc** [comment]
@lsahnicne New version release. Adds support to connecting to HTTP Servers like Apache, Nginx, MS IIS and Serve. From screnshot it looks like your server is Nginx, so that should work now.
