### ISSUE TITLE
Error 310: Could not read package header info" in EZRemoteClient

### ISSUE THREAD

**Issue by SuperUmesh** [cy33hc/ps4-ezremote-client#30]
Hi @cy33hc,

I'm encountering an issue with EZRemoteClient when trying to install files from a URL. It shows the error:

"310 Failed: Could not read package header info."

However, the same URL works perfectly with the older WebDAV Client, which downloads and installs the file without issues.

For more context, I’ve recorded a video showing the issue, which you can view [here](https://streamable.com/knuarc).

Here’s the URL you can test this issue with: https://st1.ranoz.gg/s592yc1t-Test.pkg

Thanks for your continued work on EZRemoteClient!

**Comment by cy33hc** [comment]
@SuperUmesh This is fixed and some enhancement have being implemented for "install from url"

**Comment by SuperUmesh** [comment]
Hi @cy33hc ,

I created a page where anyone can download PS4 PKG files via the PS4 web browser using EZRemoteClient. Is there any possibility you could add a resume download feature for the page?
Here’s the link for reference: [Link](https://www.superpsx.com/ps4-browser-games)
