### ISSUE TITLE
ezremote-client app with Google Drive - error

### ISSUE THREAD

**Issue by eikun79** [cy33hc/ps4-ezremote-client#5]
![111](https://user-images.githubusercontent.com/67845709/222626819-478dee03-f21e-4784-836a-6eb8731c19c9.png)
In the ezRemote client app
ezremote-client app with Google Drive
As soon as you press setting, CE-34878-0 error appears.
Cannot enter "client_id" and a "client_secret"

ezremote-client v1.02
PS4 5.05 phat Goldhen v2.3  ---> CE-34878-0
      9.00 PRO Goldhen v2.3  ---> CE-34878-0

**Comment by cy33hc** [comment]
@eikun79 Thx. I will take a look.

**Comment by cy33hc** [comment]
@eikun79 Hot fix created. Please download 1.03 just released.

**Comment by eikun79** [comment]
@cy33hc 
After work, I came home, connected to goolgle drive (= workspace) with 
ps4 5.05, installed fpkg, and ran the game without any problems.
You worked so hard making an amazing app.
Thank you so much.

**Comment by eikun79** [comment]
I have an additional question.
(I'm sorry if it's better to ask questions with a new thread)

ps4_smb_client app
Standalone This app does not require you to enter your username and password
It's accessible.

In ps4_ezremote_app, the SMB is a
must enter user name and password to access.
Without creating a username and password (PC)
Is there any way I can access it?

**Comment by cy33hc** [comment]
@eikun79 I'm not sure why is works differently. It's the same code and library that was used. I will try see what's the cause.

**Comment by devcrono** [comment]
hello @cy33hc your application is simply amazing and I would like to implement some things if possible

1 - that images are searched by CUSA and or that is presented if I had an image inside the folders in the games as an icon
2 - I would like to be able to map Team Shared Drive (shared drives) as I have one with many games there I could use my token and choose the drive ID
3 - connect to google directly without needing API
4 - work with services acount , same as rclone
5 - be able to use cloudflare works or g-index to map teamDrive

**Comment by devcrono** [comment]
@cy33hc please friend take a look at my requests if it's not too much to ask
at least small images next to folders
and be able to map Google's Team Shared Drive T_T

**Comment by cy33hc** [comment]
@devcrono Please create new thread for request. This is a bug issue.

**Comment by cy33hc** [comment]
@eikun79 Please test if this fixes smb issue which require username/password. https://drive.google.com/file/d/1Yp2MWcMo8egiPyk8I1V1hjye_FZvxp1j/view?usp=sharing

**Comment by devcrono** [comment]
> @devcrono Please create new thread for request. This is a bug issue.

ok friend i will do that.

**Comment by eikun79** [comment]
@cy33hc 
https://drive.google.com/file/d/1Yp2MWcMo8egiPyk8I1V1hjye_FZvxp1j/view?usp=sharing

They built it up and made it for us.
It's still the same thing.
I feel like something is going wrong with my PC.

Thank you for your continued support.
When I use smb, I will just enter the username/password and use it.
