### ISSUE TITLE
[Feature request] Limit concurrent downloads

### ISSUE THREAD

**Issue by oneohthree** [cy33hc/ps4-ezremote-client#6]
Is it possible to add a setting to control the number of concurrent downloads while installing PKGs?

**Comment by RandQalan** [comment]
Fw dependent

**Comment by cy33hc** [comment]
@oneohthree There's 2 modes of installation. Local install via download/install is sequential. So you are talking about Remote Package Installation? I thought the PS4 queue the installs, I think it does max 4 installs in parallel?

**Comment by oneohthree** [comment]
@cy33hc Yes, I'm talking about Remote Package Installation. As you say the PS4 does queue the installs, but IMHO 4 in parallel is too much. Anyway if you think this feature is useless, that's fine. This tool is amazing, I'm pretty happy with it.

**Comment by cy33hc** [comment]
@oneohthree If I take over the control of how PS4 queues the installs, then it would defeat the purpose of RPI. Reason you want PS4 to control the queue, is so that you can quit the ezremote-client after you have queued it in the PS4.
