### ISSUE TITLE
[bug] app won't install or download anything with long file names

### ISSUE THREAD

**Issue by steve51184** [cy33hc/ps4-ezremote-client#7]
When using the http protocol I can't install or download with long file names..

For example the file:

UP1004-CUSA00419_00-GTAVDIGITALDOWNL-A0146-V0100-CyB1K.pkg

Won't download and if I try to install it'll just say failed or the app will crash completely..

If I rename it to something smaller it'll work fine.. problem is I can't rename all files I have as some are http based so I don't have that option..

Amazing app but would love this fixed if you could thank you so much :)

**Comment by cy33hc** [comment]
@steve51184 Thx for reporting the issue. May I know what is you http server type ngnix, apache or ms iis? all three http server type is going through different code, so it would narrow down the issue.

**Comment by cy33hc** [comment]
@steve51184 New release created. Check that the long filenames are fixed.

**Comment by steve51184** [comment]
Quick test and seems to be working fine Ty.. will report back if any issues :)
