### ISSUE TITLE
[bug] can't RPI over WebDAV as 'no username'?

### ISSUE THREAD

**Issue by steve51184** [cy33hc/ps4-ezremote-client#8]
I get the error:

"Remote server requires at least a username. Remote Package Install not possible. Would you like to download package and install?"

But I have a username in the username box and a password in the password box etc etc

**Comment by cy33hc** [comment]
@steve51184 Hi. The error message is wrong. It should say the opposite. I'll correct the error message

**Comment by steve51184** [comment]
When selecting yes though it'll download then install within the app and not do it via rpi though?

**Comment by cy33hc** [comment]
Correct. RPI can't access a link that is protected. Therefore only download and install possible.

**Comment by steve51184** [comment]
Ahh I get you now ok 🙂

**Comment by steve51184** [comment]
Problem is I can't RPI over http with no user pass either.. I get this error:

"Remote HTTP Server not reachable. Remote Package Install not possible. Would you like to download package and install?"

If the server is not reachable how can it still download and install? Which it will do but the server is online..?

**Comment by cy33hc** [comment]
@steve51184 I found a bug yesterday night while trying to fix the long filename problem. If the file have spaces in it, you'll get this error. I've fixed it and will be releasing new version soon.

**Comment by steve51184** [comment]
It did indeed Ty my friend..

**Comment by cy33hc** [comment]
@steve51184 New version released. Check if it fixes issue with spaces in filename.

**Comment by steve51184** [comment]
Quick test and seems to be working fine Ty.. will report back if any issues :)
